# Generated by Django 6.0 on 2026-01-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_alter_movie_thumbnail_alter_movie_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieDetail',
        ),
    ]
